(async function () {
  const canvas = document.getElementById('canvas');
  const imageEl = document.getElementById('artworkImage');
  const stage = document.getElementById('stage');
  const titleEl = document.getElementById('title');
  const descEl = document.getElementById('description');
  const analysisEl = document.getElementById('analysis');
  const playgroundLink = document.getElementById('playgroundLink');

  const params = new URLSearchParams(window.location.search);
  const artworkId = params.get('id');

  let currentItem = null;

  function getArtworkMedia(item) {
    const candidates = [
      item?.original?.url,
      item?.originalUrl,
      item?.output?.url,
      item?.outputUrl,
      item?.image?.url,
      item?.imageUrl,
      item?.render?.url,
      item?.renderUrl,
      item?.assets?.full,
      item?.assets?.image,
      item?.assets?.preview,
      item?.previewUrl,
    ].filter(Boolean);

    const url = candidates.find(Boolean) || null;
    const width = Number(item?.original?.width || item?.output?.width || item?.image?.width || item?.presentation?.width || 0);
    const height = Number(item?.original?.height || item?.output?.height || item?.image?.height || item?.presentation?.height || 0);
    return { url, width, height };
  }

  function getAspectRatio(item) {
    const media = getArtworkMedia(item);
    if (media.width > 0 && media.height > 0) return media.width / media.height;
    return 16 / 9;
  }

  function analysisRows(item) {
    const cfg = item.defaultConfig || {};
    const p = cfg.params || {};
    const custom = item.analysis || {};

    const sourceLabel = item.source === 'original' ? '🟢 Original Output' : '🟡 Canvas Render';
    const pres = item.presentation || {};
    const dimStr = pres.width && pres.height ? `${pres.width}×${pres.height}` : '';
    const rows = [
      ['Source', sourceLabel + (dimStr ? ` (${dimStr})` : '')],
      ['Algorithm', custom.algorithm || cfg.algo || item.technique || 'N/A'],
      ['Palette', custom.palette || cfg.palette || 'N/A'],
      ['Character Set', custom.ramp || cfg.ramp || 'N/A'],
      ['Reading', custom.reading || item.analysisText || item.description || 'Generated by Glyph from algorithmic simulation.'],
      ['Notable Parameters', custom.parameters || Object.entries(p).map(([k,v]) => `${k}: ${v}`).join(' · ') || 'Default parameters'],
    ];

    return rows.map(([label, value]) => `
      <div class="analysis-item">
        <span class="label">${label}</span>
        <div class="value">${value}</div>
      </div>
    `).join('');
  }

  function renderStill(item) {
    const cfg = item.defaultConfig || {};
    const algoName = cfg.algo || 'matrix';
    const AlgoClass = ALGORITHMS[algoName] || ALGORITHMS.matrix;
    const rampName = cfg.ramp || AlgoClass.prefRamp || 'standard';
    const ramp = RAMPS[rampName] || RAMPS.standard;
    const paletteName = cfg.palette || AlgoClass.prefPalette || 'matrix';
    const paletteFn = PALETTES[paletteName] || PALETTES.matrix;

    const ratio = getAspectRatio(item);
    const box = stage.getBoundingClientRect();
    let w = Math.max(320, Math.floor(box.width));
    let h = Math.max(200, Math.floor(box.height));
    if (w / h > ratio) w = Math.floor(h * ratio);
    else h = Math.floor(w / ratio);

    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.max(1, Math.floor(w * dpr));
    canvas.height = Math.max(1, Math.floor(h * dpr));
    canvas.style.width = `${w}px`;
    canvas.style.height = `${h}px`;

    const ctx = canvas.getContext('2d');
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    const fontSize = cfg.fontSize || 14;
    const isPixelMode = AlgoClass.renderMode === 'pixel';
    const charW = isPixelMode ? 3 : Math.ceil(fontSize * 0.62);
    const charH = isPixelMode ? 3 : Math.ceil(fontSize * 1.2);
    const cols = Math.max(16, Math.floor(w / charW));
    const rows = Math.max(12, Math.floor(h / charH));

    const rng = new RNG(cfg.seed || 42);
    const algo = new AlgoClass(rows, cols, rng, ramp.length, cfg.params || {});

    const warmUpSteps = isPixelMode ? 150 : 44;
    for (let i = 0; i < warmUpSteps; i++) algo.step();
    const { chars, brightness } = algo.getState();

    ctx.fillStyle = '#000';
    ctx.fillRect(0, 0, w, h);

    const isPixelMode = AlgoClass.renderMode === 'pixel';

    if (isPixelMode) {
      for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
          const idx = r * cols + c;
          const b = brightness[idx];
          if (b < 0.005) continue;
          const [cr, cg, cb] = paletteFn(b);
          ctx.fillStyle = `rgb(${cr},${cg},${cb})`;
          ctx.fillRect(c * charW, r * charH, charW, charH);
        }
      }
    } else {
      ctx.font = `${fontSize}px 'DejaVu Sans Mono','Fira Code','Courier New',monospace`;
      ctx.textBaseline = 'top';

      for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) {
          const idx = r * cols + c;
          const b = brightness[idx];
          if (b < 0.01) continue;

          const ci = Math.min(ramp.length - 1, Math.max(0, chars[idx]));
          const ch = ramp[ci];
          if (ch === ' ') continue;

          const [cr, cg, cb] = paletteFn(b);
          ctx.fillStyle = `rgb(${cr},${cg},${cb})`;
          ctx.fillText(ch, c * charW, r * charH);
        }
      }
    }

    const fx = cfg.fx || {};
    if (fx.scanlines !== false) {
      ctx.fillStyle = 'rgba(0,0,0,0.12)';
      for (let y = 1; y < h; y += 2) ctx.fillRect(0, y, w, 1);
    }

    if (fx.vignette !== false) {
      const cx = w / 2, cy = h / 2;
      const r = Math.max(cx, cy) * 1.2;
      const grad = ctx.createRadialGradient(cx, cy, r * 0.4, cx, cy, r);
      grad.addColorStop(0, 'rgba(0,0,0,0)');
      grad.addColorStop(1, 'rgba(0,0,0,0.6)');
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, w, h);
    }
  }

  function showOriginalIfAvailable(item) {
    const media = getArtworkMedia(item);
    if (!media.url) return false;

    imageEl.hidden = false;
    canvas.hidden = true;
    imageEl.src = media.url;
    imageEl.style.aspectRatio = media.width > 0 && media.height > 0 ? `${media.width} / ${media.height}` : '';
    return true;
  }

  function attachEvents() {
    let resizeTimer;
    window.addEventListener('resize', () => {
      clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => {
        if (currentItem && canvas && !canvas.hidden) renderStill(currentItem);
      }, 220);
    });
  }

  try {
    const data = await Store.getArtworks();
    const items = data.items || [];
    const item = items.find(x => x.id === artworkId) || items[0];

    if (!item) throw new Error('No artworks found');

    currentItem = item;
    titleEl.textContent = item.title || item.id;
    descEl.textContent = item.description || '';

    // Populate artist text sections
    if (item.inspiration) {
      document.getElementById('inspirationSection').hidden = false;
      document.getElementById('inspirationText').textContent = item.inspiration;
    }
    if (item.reflection) {
      document.getElementById('reflectionSection').hidden = false;
      document.getElementById('reflectionText').textContent = item.reflection;
    }
    if (item.voiceDevelopment) {
      document.getElementById('voiceSection').hidden = false;
      document.getElementById('voiceText').textContent = item.voiceDevelopment;
    }

    analysisEl.innerHTML = analysisRows(item);

    const ratio = getAspectRatio(item);
    const ratioString = Number.isFinite(ratio) && ratio > 0 ? ratio.toFixed(4) : '';
    playgroundLink.href = `/playground.html?artwork=${encodeURIComponent(item.id)}${ratioString ? `&ratio=${encodeURIComponent(ratioString)}` : ''}`;

    if (!showOriginalIfAvailable(item)) {
      imageEl.hidden = true;
      canvas.hidden = false;
      renderStill(item);
      attachEvents();
    }
  } catch (err) {
    titleEl.textContent = 'Error';
    descEl.textContent = err.message;
  }
})();